### PR TITLE
Added new wallpaper

### PR DESCRIPTION
**Pull request by n0zhik**

### CODE REVIEW

**Review by killajoe — COMMENTED** [review]
Is this licence free?

**Comment by n0zhik** [comment]
https://webbtelescope.org/contents/media/images/01GK2KKTR81SGYF24YBGYG7TAP.html According to the Content Use Policy it is public domain 👍

**Comment by flyingcakes85** [comment]
Does the image seem too large in size? 23MB is maybe too much for a 4K wallpaper.

**Comment by gr0sz** [comment]
> Does the image seem too large in size? 23MB is maybe too much for a 4K wallpaper.

You might be right, is there anything in particular you'd recommend using to downscale it? I tend to default towards Irfanview

**Pull request merged**
